name: frontend
description: "MERIDIEN - Multi-tenant Enterprise Retail & Inventory Digital Intelligence Engine"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # HTTP & API
  dio: ^5.4.3
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # Routing
  go_router: ^13.2.0

  # Utils
  logger: ^2.2.0
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5

  # Icons
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
